version: '3'
services:
   db:
     image: habitat/postgresql
     volumes:       
       - "./updated_config.toml:/updated_config.toml"
   railsapp:
      image: taitd/sample-rails-app
      ports:
       - 8000:8000
      links: 
       - db
      command: --peer db --bind database:postgresql.default 
